// This file is auto-generated by @hey-api/openapi-ts

import { type Client, formDataBodySerializer, type Options as Options2, type TDataShape } from './client';
import { client } from './client.gen';
import { getCategoryResponseTransformer, getProductResponseTransformer, queryCategoriesResponseTransformer, queryProductsResponseTransformer } from './transformers.gen';
import type { CreateCategoryData, CreateCategoryResponses, CreateProductData, CreateProductResponses, DeleteProductData, DeleteProductResponses, GetCategoryData, GetCategoryResponses, GetProductData, GetProductResponses, QueryCategoriesData, QueryCategoriesResponses, QueryProductsData, QueryProductsResponses, UpdateCategoryData, UpdateCategoryResponses, UpdateProductData, UpdateProductResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const queryCategories = <ThrowOnError extends boolean = false>(options?: Options<QueryCategoriesData, ThrowOnError>) => (options?.client ?? client).get<QueryCategoriesResponses, unknown, ThrowOnError>({
    responseTransformer: queryCategoriesResponseTransformer,
    url: '/api/categories',
    ...options
});

export const createCategory = <ThrowOnError extends boolean = false>(options: Options<CreateCategoryData, ThrowOnError>) => (options.client ?? client).post<CreateCategoryResponses, unknown, ThrowOnError>({
    url: '/api/categories',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const getCategory = <ThrowOnError extends boolean = false>(options: Options<GetCategoryData, ThrowOnError>) => (options.client ?? client).get<GetCategoryResponses, unknown, ThrowOnError>({
    responseTransformer: getCategoryResponseTransformer,
    url: '/api/categories/{id}',
    ...options
});

export const updateCategory = <ThrowOnError extends boolean = false>(options: Options<UpdateCategoryData, ThrowOnError>) => (options.client ?? client).patch<UpdateCategoryResponses, unknown, ThrowOnError>({
    url: '/api/categories/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const queryProducts = <ThrowOnError extends boolean = false>(options?: Options<QueryProductsData, ThrowOnError>) => (options?.client ?? client).get<QueryProductsResponses, unknown, ThrowOnError>({
    responseTransformer: queryProductsResponseTransformer,
    url: '/api/products',
    ...options
});

export const createProduct = <ThrowOnError extends boolean = false>(options?: Options<CreateProductData, ThrowOnError>) => (options?.client ?? client).post<CreateProductResponses, unknown, ThrowOnError>({
    ...formDataBodySerializer,
    url: '/api/products',
    ...options,
    headers: {
        'Content-Type': null,
        ...options?.headers
    }
});

export const deleteProduct = <ThrowOnError extends boolean = false>(options: Options<DeleteProductData, ThrowOnError>) => (options.client ?? client).delete<DeleteProductResponses, unknown, ThrowOnError>({ url: '/api/products/{id}', ...options });

export const getProduct = <ThrowOnError extends boolean = false>(options: Options<GetProductData, ThrowOnError>) => (options.client ?? client).get<GetProductResponses, unknown, ThrowOnError>({
    responseTransformer: getProductResponseTransformer,
    url: '/api/products/{id}',
    ...options
});

export const updateProduct = <ThrowOnError extends boolean = false>(options: Options<UpdateProductData, ThrowOnError>) => (options.client ?? client).patch<UpdateProductResponses, unknown, ThrowOnError>({
    ...formDataBodySerializer,
    url: '/api/products/{id}',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});
