// This file is auto-generated by @hey-api/openapi-ts

import type { GetCategoryResponse, GetProductResponse, QueryCategoriesResponse, QueryProductsResponse } from './types.gen';

const categoryDtoSchemaResponseTransformer = (data: any) => {
    data.createdAt = new Date(data.createdAt);
    if (data.updatedAt) {
        data.updatedAt = new Date(data.updatedAt);
    }
    return data;
};

export const queryCategoriesResponseTransformer = async (data: any): Promise<QueryCategoriesResponse> => {
    data = data.map((item: any) => categoryDtoSchemaResponseTransformer(item));
    return data;
};

export const getCategoryResponseTransformer = async (data: any): Promise<GetCategoryResponse> => {
    data = categoryDtoSchemaResponseTransformer(data);
    return data;
};

const productDtoSchemaResponseTransformer = (data: any) => {
    data.category = categoryDtoSchemaResponseTransformer(data.category);
    data.createdAt = new Date(data.createdAt);
    if (data.updatedAt) {
        data.updatedAt = new Date(data.updatedAt);
    }
    return data;
};

const getProductsDtoSchemaResponseTransformer = (data: any) => {
    data.items = data.items.map((item: any) => productDtoSchemaResponseTransformer(item));
    return data;
};

export const queryProductsResponseTransformer = async (data: any): Promise<QueryProductsResponse> => {
    data = getProductsDtoSchemaResponseTransformer(data);
    return data;
};

export const getProductResponseTransformer = async (data: any): Promise<GetProductResponse> => {
    data = productDtoSchemaResponseTransformer(data);
    return data;
};
