// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:5132' | (string & {});
};

export type CategoryDto = {
    id: number;
    name: string | null;
    description: string | null;
    isActive: boolean;
    displayOrder: number;
    parentId: number | null;
    createdAt: Date;
    updatedAt: Date | null;
};

export type CreateUpdateCategoryDto = {
    name: string | null;
    description: string | null;
    isActive: boolean;
    displayOrder: number;
    parentId: number | null;
};

export type CreateUpdateProductDto = {
    name: string | null;
    description: string | null;
    price: number;
    image: Blob | File | null;
    categoryId: number | null;
    customAttributes: string | null;
};

export type ProductDto = {
    id: number;
    name: string | null;
    description: string | null;
    price: number;
    imagePath: string | null;
    category: CategoryDto;
    customAttributes: string | null;
    createdAt: Date;
    updatedAt: Date | null;
};

export type QueryCategoriesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/categories';
};

export type QueryCategoriesResponses = {
    /**
     * OK
     */
    200: Array<CategoryDto>;
};

export type QueryCategoriesResponse = QueryCategoriesResponses[keyof QueryCategoriesResponses];

export type CreateCategoryData = {
    body: CreateUpdateCategoryDto;
    path?: never;
    query?: never;
    url: '/api/categories';
};

export type CreateCategoryResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetCategoryData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/categories/{id}';
};

export type GetCategoryResponses = {
    /**
     * OK
     */
    200: CategoryDto;
};

export type GetCategoryResponse = GetCategoryResponses[keyof GetCategoryResponses];

export type UpdateCategoryData = {
    body: CreateUpdateCategoryDto;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/categories/{id}';
};

export type UpdateCategoryResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type QueryProductsData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        name?: string;
        description?: string;
        minPrice?: number;
        maxPrice?: number;
        customAttributes?: string;
        category?: string;
    };
    url: '/api/products';
};

export type QueryProductsResponses = {
    /**
     * OK
     */
    200: Array<ProductDto>;
};

export type QueryProductsResponse = QueryProductsResponses[keyof QueryProductsResponses];

export type CreateProductData = {
    body?: {
        data: CreateUpdateProductDto;
    };
    path?: never;
    query?: never;
    url: '/api/products';
};

export type CreateProductResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type DeleteProductData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/products/{id}';
};

export type DeleteProductResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetProductData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/products/{id}';
};

export type GetProductResponses = {
    /**
     * OK
     */
    200: ProductDto;
};

export type GetProductResponse = GetProductResponses[keyof GetProductResponses];

export type UpdateProductData = {
    body?: {
        data: CreateUpdateProductDto;
    };
    path: {
        id: number;
    };
    query?: never;
    url: '/api/products/{id}';
};

export type UpdateProductResponses = {
    /**
     * OK
     */
    200: unknown;
};
